#!/bin/bash

CDN=http://dl-cdn.alpinelinux.org/alpine
ARCHES=(x86 armhf aarch64 ppc64le s390x)

VERSION=$DOCKER_TAG
SHORTVER=${VERSION%.*}

download_rootfs() {
	local arch=$1; shift

	local filename="alpine-minirootfs-$VERSION-$arch.tar.gz"
	local url="$CDN/v$SHORTVER/releases/$arch/$filename"

	echo "Downloading $url"
	curl --progress -LO "$url"
	echo "Verifying archive integrity..."
	curl -Ss -L "$url.sha256" | sha256sum -c
}

docker build -t ld-qemu-build qemu-static
mkdir -p ld-qemu
chmod g+s ld-qemu
docker run --rm -v $(pwd)/ld-qemu:/output -it ld-qemu-build

for arch in ${ARCHES[@]}; do
	download_rootfs $arch
	docker build -t $IMAGE_NAME:$arch-$SHORTVER .
done

# Special-casing x86_64 because it would be ridiculous to run with qemu.
docker pull alpine:$SHORTVER
docker tag alpine:$SHORTVER $IMAGE_NAME:x86_64-$SHORTVER
